[workspace]
channels = ["conda-forge"]
name = "ai_governance_healthcare"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.11,<3.13"

[pypi-dependencies]
zensical = "*"

[tasks]
docs-serve = "zensical serve"
docs-build = "zensical build"
