"""Scripts run both ways: by scripts/check_app.py and by node (#176).

Each is (name, script, throws): `throws` is True when the script throws a
ReferenceError while it loads, as a classic script in a fresh context (thrown,
or an async function's rejection before the script's timers run), and False
when it raises nothing. tests/test_check_app.py runs every script in node and
requires node to agree with `throws`, and requires check-app to report a
problem exactly when it is True. So each row is a case on which the check is
shown to be exact against the engine, not by assertion.

What is not here, on purpose: the duplicate rule (a policy, not a runtime
error), comparisons that are not a typeof guard and whose branch therefore
does not run in node (the check reports them because it cannot prove them
safe), and the over-approximations listed in check_app's docstring. Those are
unit tests in test_check_app.py.
"""

from __future__ import annotations

ENGINE_CASES: list[tuple[str, str, bool]] = [
    # typeof guards: a guarded read of a name nothing declares, which never runs,
    # and the forms that do run it
    ("g1_eq_loose_rev", 'if ("function" == typeof zz) zz();', False),
    ("g2_ne_loose_rev_undef", 'if ("undefined" != typeof zz) zz();', False),
    ("g3_single_quotes", "if (typeof zz != 'undefined') zz();", False),
    ("g4_u4_escape", 'if (typeof zz === "function") zz();', False),
    ("g5_ubrace_escape", 'if (typeof zz === "\\u{66}unction") zz();', False),
    ("g6_line_cont", 'if (typeof zz === "func\\\ntion") zz();', False),
    ("g7_octal_escape", 'if (typeof zz === "\\146unction") zz();', False),
    ("g11_undef_consequent", 'if (typeof zz === "undefined") zz();', True),
    ("g13_tern_ok", 'typeof zz === "function" ? zz() : 0;', False),
    ("g14_tern_alt", 'typeof zz === "function" ? 0 : zz();', True),
    ("g15_and", 'typeof zz === "function" && zz();', False),
    ("g16_or", 'typeof zz === "function" || zz();', True),
    ("g17_paren_cond_and", '(typeof zz === "function") && zz();', False),
    ("g18_paren_typeof", '((typeof zz) === "function") && zz();', False),
    ("g19_typeof_paren_arg", 'typeof (zz) === "function" && zz();', False),
    ("g20_typeof_dbl_paren_arg", 'typeof ((zz)) === "object" && zz.x;', False),
    ("g21_paren_string", 'typeof zz === ("function") && zz();', False),
    (
        "g22_two_names_chain",
        'typeof zz === "function" && typeof yy === "function" && (zz(), yy());',
        False,
    ),
    ("g23_and_then_1", 'if (typeof zz === "function" && 1) zz();', False),
    ("g24_1_and", 'if (1 && typeof zz === "function") zz();', False),
    (
        "g29_nested_iife_in_branch",
        'if (typeof zz === "function") { (function(){ zz(); })(); }',
        False,
    ),
    (
        "g30_callback_in_branch",
        'if (typeof zz === "function") { setTimeout(() => zz()); }',
        False,
    ),
    (
        "g31_else_if_chain",
        'if (typeof zz === "function") zz(); else if (typeof zz === "object") zz.x;',
        False,
    ),
    ("g32_after_if", 'if (typeof zz === "function") {} zz;', True),
    (
        "g33_tern_two_names",
        'typeof zz === "function" && typeof yy === "function" ? zz() + yy() : 0;',
        False,
    ),
    ("g34_symbol", 'typeof zz === "symbol" && zz;', False),
    ("g35_bigint", 'typeof zz === "bigint" && zz;', False),
    ("g36_boolean_loose", 'typeof zz == "boolean" && zz;', False),
    ("g37_string", 'typeof zz === "string" && zz.length;', False),
    ("g38_number", 'typeof zz === "number" && zz + 1;', False),
    ("g42_tern_ne_escaped_undef", 'typeof zz !== "\\x75ndefined" ? zz : 0;', False),
    ("g43_ne_u_escape", 'typeof zz !== "undefined" && zz;', False),
    ("g44_backslash_n_not_undef", 'typeof zz !== "undefi\\ned" && zz;', True),
    ("g45_vtab", 'typeof zz != "\\v" && zz;', True),
    ("g46_call_this", 'typeof zz === "function" && zz.call(this);', False),
    ("g47_new", "typeof zz === 'function' && new zz();", False),
    ("g48_typeof_member", 'typeof zz.y === "function" && zz.y();', True),
    ("g49_typeof_optional", 'typeof zz?.y === "function";', True),
    ("g50_typeof_comma", 'typeof (0, zz) === "function";', True),
    ("g51_bare_typeof", "typeof zz;", False),
    ("g52_typeof_typeof", "typeof typeof zz;", False),
    ("g53_void_typeof", "void typeof zz;", False),
    ("g54_var_in_branch", 'if (typeof zz === "function") var q = zz;', False),
    (
        "g55_if_function_decl",
        'if (typeof zz === "function") function hh(){ return zz; }',
        False,
    ),
    ("g57_and_comma", 'typeof zz === "function" && (zz(), 1);', False),
    ("g58_and_and_call", 'typeof zz === "function" && zz() && zz();', False),
    ("g59_and_or_call", 'typeof zz === "function" && zz() || zz();', True),
    ("g62_other_name_after", 'if (typeof zz === "function") zz(); zz2;', True),
    ("g63_empty_consequent", 'if (typeof zz === "function"); zz();', True),
    (
        "g64_block_let_then_guard",
        '{ let zz = 1; } typeof zz === "function" && zz();',
        False,
    ),
    (
        "g65_two_tests_same",
        'if (typeof zz === "function" && typeof zz !== "undefined") zz();',
        False,
    ),
    ("g67_let_in_branch", 'if (typeof zz === "function") { let zz2 = zz; }', False),
    ("g68_assign_guarded_value", 'var x = typeof zz === "function" && zz;', False),
    ("g71_u_escaped_undef_consequent", 'if (typeof zz === "undefined") zz();', True),
    ("g72_hex_rev", 'if ("\\x66unction" == typeof zz) zz();', False),
    ("g73_comment_after_cond", 'if (typeof zz === "function" /*c*/) zz();', False),
    ("g74_comment_before_cond", 'if (/*c*/ typeof zz === "function") zz();', False),
    ("g75_comment_in_binary", 'if (typeof zz === /*c*/ "function") zz();', False),
    ("g76_comment_in_and", 'typeof zz === "function" && /*c*/ zz();', False),
    (
        "g77_comment_before_consequent",
        'if (typeof zz === "function") /*c*/ zz();',
        False,
    ),
    ("g78_line_comment_paren", 'if (typeof zz === "function" // c\n) zz();', False),
    ("g79_double_paren_cond", 'if ((typeof zz === "function")) zz();', False),
    ("g80_paren_call", 'typeof zz === "function" ? (zz)() : 0;', False),
    ("g81_ubrace_padded", 'typeof zz === "\\u{0066}unction" && zz();', False),
    ("g82_two_hex", 'typeof zz === "\\x66\\x75nction" && zz();', False),
    ("g83_nul_prefix", 'typeof zz !== "\\0undefined" && zz;', True),
    ("g85_line_cont_end", 'typeof zz !== "undefined\\\n" && zz;', False),
    ("g86_u2028_escape", 'typeof zz !== "undefined\u2028" && zz;', True),
    ("g90_identity_escapes", 'typeof zz === "\\obje\\ct" && zz;', False),
    ("g91_octal_u", 'typeof zz !== "\\165ndefined" && zz;', False),
    ("g92_octal_then_digit", 'typeof zz !== "\\1650ndefined" && zz;', True),
    ("g93_backslash_8", 'typeof zz !== "\\8undefined" && zz;', True),
    ("g95_mid_hex", 'typeof zz !== "un\\x64efined" && zz;', False),
    ("g96_crlf_suffix", 'typeof zz !== "undefined\\r\\n" && zz;', True),
    ("g97_crlf_line_cont", 'typeof zz !== "undefi\\\r\nned" && zz;', False),
    ("g98_u4_full", 'typeof zz !== "undefined" && zz;', False),
    ("g99_ubrace_long", 'typeof zz !== "\\u{000075}ndefined" && zz;', False),
    ("g100_single_undef", "typeof zz !== 'undefined' && zz;", False),
    ("g101_octal_0", 'typeof zz !== "\\0" && zz;', True),
    ("g106_octal_7_then_digits", 'typeof zz !== "\\7undefined" && zz;', True),
    ("g108_and_in_else", 'if (0) {} else typeof zz === "function" && zz();', False),
    (
        "g109_tern_in_consequent",
        'typeof zz === "function" ? (typeof yy === "function" ? yy() : zz()) : 0;',
        False,
    ),
    ("g110_nested_and_right_side", '1 && (typeof zz === "function" && zz());', False),
    # the temporal dead zone: destructuring order, computed keys, what runs
    # immediately, generators, `delete`, async code, and the call graph
    ("t1_obj_default_later", "const {a = b, b} = {};", True),
    ("t2_obj_default_earlier", "const {b, a = b} = {};", False),
    ("t3_arr_default_later", "const [a = b, b] = [];", True),
    ("t4_arr_default_earlier", "const [b, a = b] = [];", False),
    ("t5_obj_computed_key_later", "const {[b]: a, b} = {};", True),
    ("t6_obj_computed_key_earlier", 'const {b, [b]: a} = {b: "k"};', False),
    ("t7_nested_default_later", "const {a: {c = b}, b} = {a: {}};", True),
    ("t8_nested_earlier", "const {b: {c}, d = c} = {b: {}};", False),
    ("t9_iife_in_default_later", "const [a = (() => b)(), b] = [];", True),
    ("t10_arrow_in_default_called_later", "const [a = () => b, b] = []; a();", False),
    ("t11_other_declarator_later", "let {a = b} = {}, b;", True),
    ("t12_other_declarator_earlier", "let b = 1, {a = b} = {};", False),
    ("t13_self_default", "const {a = a} = {};", True),
    ("t14_rest_self_init", "const {...r} = r;", True),
    ("t15_arr_rest_self_init", "const [...r] = [r];", True),
    ("t16_chain_defaults", "const {a, b = a, c = b} = {a: 1};", False),
    ("t17_renamed_default_later", "const {x: a = b, y: b} = {};", True),
    ("t18_renamed_earlier", "const {x: b, y: a = b} = {};", False),
    ("t19_nested_arr_later", "const [[a = b], b] = [[]];", True),
    ("t20_forof_obj_default_later", "for (const {a = b, b} of [{}]);", True),
    ("t21_forof_obj_default_earlier", "for (const {b, a = b} of [{}]);", False),
    ("t22_forof_arr_earlier", "for (const [b, a = b] of [[]]);", False),
    ("t23_forof_body_pattern", "for (const x of [1]) { const {y = x} = {}; }", False),
    (
        "t24_forof_default_reads_toplevel_later",
        "for (const {a = x} of [{}]) {} const x = 1;",
        True,
    ),
    ("t26_forin_self", "for (const a in a) {}", True),
    ("t27_obj_computed_self", "const a = {[a]: 1};", True),
    ("t28_obj_computed_later", 'const o = {[k]: 1}; const k = "x";', True),
    ("t29_obj_computed_method_later", 'const o = { [k]() {} }; const k = "x";', True),
    (
        "t30_obj_computed_getter_later",
        'const o = { get [k]() {} }; const k = "x";',
        True,
    ),
    ("t31_class_field_key_later", 'class C { [k] = 1 } const k = "x";', True),
    (
        "t32_class_static_field_key_later",
        "class C { static [k] = 1 } const k = 1;",
        True,
    ),
    ("t33_class_method_key_later", "class C { [k]() {} } const k = 1;", True),
    (
        "t34_class_static_method_key_later",
        "class C { static [k]() {} } const k = 1;",
        True,
    ),
    (
        "t35_key_in_method_body",
        "class C { m() { return {[k]: 1}; } } const k = 1;",
        False,
    ),
    (
        "t36_obj_method_body_key_called_after",
        "const o = { m() { return {[k]:1}; } }; const k = 1; o.m();",
        False,
    ),
    ("t37_class_key_reads_own_name", "class C { [C]() {} }", True),
    (
        "t38_class_expr_static_key_own_name",
        "const D = class C { static [C] = 1 };",
        True,
    ),
    ("t39_class_field_key_own_name", "class C { [C.name] = 1 }", True),
    (
        "t40_static_field_own_name",
        "class C { static x = C; }",
        False,
    ),
    ("t41_static_block_own_name", "class C { static { C; } }", False),
    ("t42_new_function_later", "new function(){ k; }; const k = 1;", True),
    ("t44_generator_iife", "(function*(){ k; })(); const k = 1;", False),
    ("t46_generator_decl_called", "function* g(){ k; } g(); const k = 1;", False),
    ("t47_delete_tdz", "delete k; const k = 1;", False),
    ("t48_delete_paren", "delete (k); const k = 1;", False),
    ("t49_delete_dbl_paren", "delete ((k)); const k = 1;", False),
    ("t50_typeof_tdz", "typeof k; const k = 1;", True),
    ("t51_void_tdz", "void k; const k = 1;", True),
    ("t52_assign_tdz", "k = 1; let k;", True),
    ("t53_incr_tdz", "k++; let k;", True),
    ("t54_pattern_assign_tdz", "({k} = {}); let k;", True),
    ("t55_arr_pattern_assign_tdz", "[k] = []; let k;", True),
    ("t58_fn_called", "function f(){ return k; } f(); const k = 1;", True),
    (
        "t59_fn_expr_called",
        "const f = function(){ return k; }; f(); const k = 1;",
        True,
    ),
    ("t60_let_arrow_called", "let f = () => k; f(); let k;", True),
    ("t61_var_arrow_called", "var f = () => k; f(); let k;", True),
    ("t62_ctor", "class K { constructor(){ k; } } new K(); const k = 1;", True),
    ("t63_instance_field", "class K { x = k; } new K(); const k=1;", True),
    ("t64_instance_field_arrow", "class K { x = () => k; } new K(); const k=1;", False),
    (
        "t65_instance_field_iife",
        "class K { x = (() => k)(); } new K(); const k=1;",
        True,
    ),
    ("t69_chain_g", "function f(){ g(); } function g(){ k; } f(); const k = 1;", True),
    ("t70_block_in_fn", "f(); function f(){ { k; } } const k = 1;", True),
    ("t71_shadowed_in_fn", "function f(){ let k; return k; } f(); const k = 1;", False),
    (
        "t72_typeof_in_called_fn",
        "function f(){ return typeof k; } f(); const k=1;",
        True,
    ),
    ("t73_delete_in_called_fn", "function f(){ delete k; } f(); const k=1;", False),
    (
        "t74_guard_in_called_fn",
        'function f(){ if (typeof k === "number") k; } f(); let k;',
        True,
    ),
    ("t75_async_before_await", "(async () => { k; await 0; })(); const k = 1;", True),
    ("t76_async_after_await", "(async () => { await 0; k; })(); const k=1;", False),
    (
        "t77_async_after_await_paren",
        "(async () => { await (0); k; })(); const k=1;",
        False,
    ),
    (
        "t78_misparsed_await_then_read",
        "(async () => { await (p)(); k; })(); const k = 1; function p(){}",
        False,
    ),
    (
        "t79_misparsed_await_member",
        "(async () => { await (p)().then; k; })(); const k = 1;"
        " function p(){ return {}; }",
        False,
    ),
    (
        "t80_misparsed_await_operand_reads",
        "(async () => { await (k)(); })(); const k = 1;",
        True,
    ),
    ("t81_await_as_fn_name", "function await(x){} await (k); const k = 1;", True),
    ("t82_await_undefined_name", "await (1);", True),
    (
        "t83_direct_after_async_call",
        "async function f(){ await 0; } f(); k; const k=1;",
        True,
    ),
    ("t84_async_arrow_expr_body", "const k2 = (async () => k)(); const k = 1;", True),
    (
        "t85_for_await_rhs",
        "(async function(){ for await (const x of [k]) {} })(); const k = 1;",
        True,
    ),
    (
        "t86_after_for_await",
        "(async function(){ for await (const x of []) {} k; })(); const k=1;",
        False,
    ),
    ("t87_new_paren_fn", "new (function(){ k; }); const k = 1;", True),
    ("t88_new_paren_fn_call", "new (function(){ k; })(); const k=1;", True),
    (
        "t89_new_arrow",
        "try { new (() => { k; })(); }"
        " catch (e) { if (!(e instanceof TypeError)) throw e; } const k = 1;",
        False,
    ),
    ("t90_new_function_this", "new function(){ this.x = k; }; const k=1;", True),
    (
        "t91_static_field_fn_iife",
        "class K { static f = function(){ return k; }(); } const k=1;",
        True,
    ),
    ("t92_obj_key_iife", "const o = { [(() => k)()]: 1 }; const k=1;", True),
    ("t93_obj_value_iife", "const o = { a: (() => k)() }; const k=1;", True),
    (
        "t94_field_fn_expr",
        "class K { f = function(){ return k; } } new K(); const k=1;",
        False,
    ),
    ("t95_field_ternary", "class K { f = k ? 1 : 2 } new K(); const k=1;", True),
    ("t96_heritage_comma", "class A extends (k, Object) {} const k=1;", True),
    (
        "t97_class_expr_heritage",
        "const A = class extends k {}; const k = Object;",
        True,
    ),
    ("t98_switch_case", "switch (1) { case k: } const k = 1;", True),
    ("t99_arr_nested_default_pattern", "const [{a} = b, b] = [];", True),
    ("t100_arr_nested_inner_default", "const [{a = b} = {}, b] = [];", True),
    ("t101_arr_earlier_nested", "const [b = 1, {a = b} = {}] = [];", False),
    ("t102_paren_default", "const {a = (b)} = {}, b=1;", True),
    ("t103_let_mutual", "let [x = y, y = x] = [];", True),
    ("t104_chain_with_defaults", "const {b = 1, a = b, c = a} = {};", False),
    ("t105_computed_key_outer_later", 'const {[k]: {a = k}} = {x: {}}, k = "x";', True),
    ("t106_default_arrow_later_called", "const {a = () => b, b} = {}; a();", False),
    ("t107_default_iife_obj_later", "const {a = (() => b)(), b} = {};", True),
    ("t108_arr_default_earlier", "const [a, b = a] = [1];", False),
    ("t109_computed_key_self", "const {[a]: a} = {};", True),
    ("t110_nested_arr_self", "const {x: [a = a]} = {x: []};", True),
    ("t111_forof_body_read", "for (const {a} of [{a: 1}]) { a; }", False),
    ("t112_forof_chain_defaults", "for (const {a = 1, b = a} of [{}]);", False),
    (
        "t113_delete_member",
        "try { delete k.x; } catch (e) { throw e; } const k = {};",
        True,
    ),
    ("t114_delete_comma", "delete (0, k); const k=1;", True),
    (
        "t115_gen_expr_called_as_value",
        "const g = function*(){ k; }(); const k = 1;",
        False,
    ),
    ("t116_async_gen_iife", "(async function*(){ k; })(); const k = 1;", False),
    ("t117_class_static_block_later", "class K { static { k; } } const k = 1;", True),
    (
        "t118_static_block_iife_inner",
        "class K { static { (() => k)(); } } const k = 1;",
        True,
    ),
    ("t119_computed_key_in_iife", "(() => ({[k]: 1}))(); const k = 1;", True),
    (
        "t120_class_in_iife_key",
        "(() => { class C { [k]() {} } })(); const k = 1;",
        True,
    ),
    (
        "t121_class_field_key_after_ready",
        'const k = "a"; class C { [k] = 1; static [k] = 2; [k]() {} }',
        False,
    ),
    ("t122_obj_shorthand_tdz", "const o = { k }; const k = 1;", True),
    ("t123_template_tdz", "`${k}`; const k = 1;", True),
    ("t124_tagged_template_fn", "f`x`; function f(){ return k; } const k = 1;", True),
    ("t125_spread_tdz", "[...k]; const k = [];", True),
    ("t126_optional_chain_tdz", "k?.x; const k = 1;", True),
    ("t127_label_block", "lbl: { k; } const k = 1;", True),
    ("t128_inner_block_later_decl", "{ k; let k = 1; }", True),
    (
        "t129_fn_name_in_own_body_tdz",
        "const f = function g(){ return k; }; f(); const k = 1;",
        True,
    ),
    ("t130_class_new_before", "new K(); class K {}", True),
    ("t131_class_name_in_method_later", "class K { m(){ return K; } }", False),
    ("t132_var_shadow_no_tdz", "var k2 = 1; { k2; }", False),
    ("t133_shadow_param", "function f(k){ return k; } f(); const k = 1;", False),
    (
        "t134_default_param_reads_toplevel",
        "function f(a = k){ return a; } f(); const k = 1;",
        True,
    ),
    (
        "t135_catch_param_shadow",
        "try { throw 1; } catch (k) { k; } const k = 1;",
        False,
    ),
    # Annex B: block functions a lexical declaration blocks
    ("d1_let_then_if_fn", "let f; if (1) function f(){}", False),
    ("d2_const_after_if_fn", "if (1) function f(){} const f = 1;", False),
    ("d4_block_fn_and_other_block_let", "{ function f(){} } { let f; }", False),
    ("d5_block_let_around", "function f(){} { let f; { function f(){} } }", False),
    (
        "d9_switch_let_other_block",
        "switch (1) { case 1: let f; } { function f(){} }",
        False,
    ),
    ("d11_block_fn_class_after", "{ function f(){} } class f {}", False),
    (
        "d13_block_fn_vs_let_in_switch_around",
        "function f(){} switch (1) { case 1: let f; { function f(){} } }",
        False,
    ),
    (
        "d14_block_fn_vs_class_in_block_around",
        "var f; { class f {} { function f(){} } }",
        False,
    ),
    ("d15_for_let_head_blocks", "var f; for (let f of []) { function f(){} }", False),
    ("d17_fn_in_fn_no_dup", "function f(){} function h(){ { function f(){} } }", False),
    ("d19_let_let_two_blocks_ok", "{ let a; } { let a; }", False),
    ("d20_class_twice_blocks", "{ class A {} } { class A {} }", False),
    (
        "d21_static_block_fn",
        "function f(){} class C { static { { function f(){} } } }",
        False,
    ),
    ("d22_param_name_fn_in_block", "function h(f){ { function f(){} } } var f;", False),
    # undefined names
    ("u1_delete_undeclared", "delete zz;", False),
    ("u2_static_block_var", "class A { static { var v = 1; } } v;", True),
    ("u3_block_var", "{ var v2 = 1; } v2;", False),
    ("u4_inner_block_fn_outside_fn", "function g(){ { function bf2(){} } } bf2;", True),
    ("u5_for_let_after", "for (let j = 0; j < 1; j++) {} j;", True),
    ("u6_labeled_fn", "label: function lf(){} lf();", False),
    (
        "u7_named_fn_expr_outside",
        "const fn = function named(){ return named; }; fn(); named;",
        True,
    ),
    (
        "u8_named_class_expr_outside",
        "const C = class Named { m(){ return Named; } }; new C().m(); Named;",
        True,
    ),
    ("u9_shorthand_undefined", "var o = { zz4 };", True),
    ("u10_quoted_key", 'var o = { "zz5": zz5 };', True),
    ("u11_catch_optional_binding_read", "try { throw 1 } catch { zz3; }", True),
    (
        "u12_private_in",
        "class A { #p = 1; m(){ return #p in this; } } new A().m();",
        False,
    ),
    (
        "u13_param_destructure_defaults",
        "function f({a} = {}, [b] = []){ return [a, b]; } f();",
        False,
    ),
    ("u14_arrow_destructure", "((a, {b}) => a + b)(1, {b:2});", False),
    ("u15_new_target", "function F(){ return new.target; } new F();", False),
    ("u16_async_name", "let async = 1; async;", False),
    ("u17_of_name", "var of = [1]; for (var x of of);", False),
    ("u18_yield_name", "var yield_ = 1; yield_;", False),
    ("u19_class_fields_this", "class A { x = this; static y = this; } new A();", False),
    (
        "u20_object_method_super",
        "var o = { m(){ return super.toString; } }; o.m();",
        False,
    ),
    # comments, `delete` through calls, Annex B in `if` bodies, a class's own
    # name in its keys
    ("h1_comment_in_typeof_paren", 'typeof (zz /*c*/) === "function" && zz();', False),
    (
        "h2_comment_in_paren_left_of_and",
        '(typeof zz === "function" /*c*/) && zz();',
        False,
    ),
    ("h3_comment_in_paren_string", 'typeof zz === ("function" /*c*/) && zz();', False),
    (
        "h4_comment_in_tern_consequent",
        'typeof zz === "function" ? /*c*/ zz() : 0;',
        False,
    ),
    (
        "h5_comment_in_tern_paren_cond",
        '(/*c*/ typeof zz === "function") ? zz() : 0;',
        False,
    ),
    (
        "h6_delete_dbl_paren_in_called_fn",
        "function f(){ delete ((k)); } f(); const k = 1;",
        False,
    ),
    (
        "h7_delete_in_chain",
        "function f(){ g(); } function g(){ delete k; } f(); const k = 1;",
        False,
    ),
    (
        "h8_call_in_pattern_default_later",
        "const {a = f(), b} = {}; function f(){ return b; }",
        True,
    ),
    (
        "h9_call_in_pattern_default_earlier",
        "const {b, a = f()} = {}; function f(){ return b; }",
        False,
    ),
    ("h10_let_else_if_fn", "let f; if (0) ; else function f(){}", False),
    ("h11_class_then_if_fn", "class f {} if (1) function f(){}", False),
    ("h12_class_getter_key_own_name", "class C { get [C]() {} }", True),
    ("h13_class_async_static_key_own_name", "class C { static async [C]() {} }", True),
    ("h14_class_bare_field_key_own_name", "class C { [C] }", True),
    ("h15_class_key_iife_own_name", "class C { [(() => C)()]() {} }", True),
    ("h16_class_key_after_static", "class C { static x = 1; [C.x] = 2 }", True),
    ("h17_nested_class_in_method", "class C { m() { class D { [C]() {} } } }", False),
    (
        "h18_nested_class_in_static_block",
        "class C { static { class D { [C] = 1 } } }",
        False,
    ),
    ("h19_delete_paren_undeclared", "delete (zz);", False),
    ("h20_if_delete_undeclared", "if (delete zz) 1;", False),
    ("h21_iife_comment", "(/*c*/ function(){ k; })(); const k = 1;", True),
    ("h22_call_comment", "(f /*c*/)(); function f(){ return k; } const k = 1;", True),
    ("h23_comment_typeof_arg", 'typeof /*c*/ zz === "function" && zz();', False),
    ("h24_class_expr_anon_key", "const D = class { [D]() {} };", True),
    ("h25_heritage_own_name_expr", "const D = class C extends (C, Object) {};", True),
    # a class's own name in its computed keys
    ("own_name_method_key", "class C { [C]() {} }", True),
    ("own_name_getter_key", "class C { get [C]() { return 1; } }", True),
    ("own_name_static_async_key", "class C { static async [C]() {} }", True),
    ("own_name_bare_field_key", "class C { [C] }", True),
    ("own_name_field_key_member", "class C { [C.name] = 1 }", True),
    ("own_name_key_after_static_field", "class C { static x = 1; [C.x] = 2 }", True),
    ("own_name_key_iife", "class C { [(() => C)()]() {} }", True),
    ("own_name_class_expr_static_key", "const D = class C { static [C] = 1 };", True),
    (
        "own_name_outside_keys",
        "class C { static x = C; static { C; } m() { return C; } }\n"
        "class E { m() { class D { [E]() {} } } static { class F { [E] = 1 } } }\n"
        "new E().m();",
        False,
    ),
    (
        "own_name_in_nested_class_in_key",
        "class C { [class D { [C]() {} }]() {} }",
        True,
    ),
    ("own_name_heritage", "class C extends (C, Object) {}", True),
    # a comment does not make a guard of a comma expression
    ("comment_comma_not_guard", 'typeof (0 /*c*/, zz) === "function" && zz();', True),
    # \8 and \9 in a guard's string
    ("backslash_8", 'if (typeof zz !== "\\8") zz();', True),
    ("backslash_9_prefix", 'if (typeof zz !== "\\9undefined") zz();', True),
    ("backslash_9_suffix", 'if (typeof zz !== "undefined\\9") zz();', True),
    # `delete` of an undeclared name
    ("delete_undeclared", "delete zz;", False),
    ("delete_paren_undeclared", "delete (zz);", False),
    ("if_delete_undeclared", "if (delete zz) 1;", False),
    ("delete_comma_undeclared", "delete (0, zz);", True),
    # `delete` in a function called during load
    ("delete_in_called_fn", "function f(){ delete a; }\nf();\nconst a = 1;", False),
    (
        "delete_dbl_paren_in_called_fn",
        "function f(){ delete ((a)); }\nf();\nconst a = 1;",
        False,
    ),
    (
        "delete_in_call_chain",
        "function f(){ g(); }\nfunction g(){ delete a; }\nf();\nconst a = 1;",
        False,
    ),
    (
        "delete_member_in_called_fn",
        "function f(){ delete a.x; }\nf();\nconst a = {};",
        True,
    ),
    # a function as the body of an `if` or `else` (B.3.3)
    ("let_then_if_fn", "let f;\nif (1) function f(){}", False),
    ("if_fn_then_const", "if (1) function f(){}\nconst f = 1;", False),
    ("let_then_else_fn", "let f;\nif (0) ;\nelse function f(){}", False),
    ("class_then_if_fn", "class f {}\nif (1) function f(){}", False),
    ("if_fn_in_fn_not_global", "function g(){ if (1) function f(){} }\ng(); f;", True),
    ("if_fn_called", "if (1) function f(){ return 1; }\nf();", False),
    # two block functions of one name, and a parameter of that name
    (
        "two_block_fns_last_reads",
        "{ function f(){} }\n{ function f(){ return a; } }\nf();\nconst a = 1;",
        True,
    ),
    (
        "block_fn_over_fn_reads",
        "function f(){} { function f(){ return a; } } f(); const a = 1;",
        True,
    ),
    (
        "block_fn_param_name",
        "function h(f){ { function f(){ return a; } } return f(); }"
        " h(() => 1); const a = 1;",
        False,
    ),
]
