"""Every endpoint in the store contract, and nothing else.

The browser persists through six methods. Each maps to one route:

================================  ==========================================
``subscribeAll(cb, err)``         ``GET /api/projects`` + ``GET /api/events``
``create(id, data)``              ``POST /api/projects/{id}``
``update(id, patch)``             ``PATCH /api/projects/{id}``
``remove(id)``                    ``DELETE /api/projects/{id}``
``log(id, entry)``                ``POST /api/projects/{id}/log``
``subscribeLog(id, cb)``          ``GET /api/projects/{id}/log`` + events
================================  ==========================================

The two ``subscribe*`` methods are a fetch plus a stream: the client fetches
once, then holds ``/api/events`` open and refetches whatever an event says
changed.
"""

from __future__ import annotations

import asyncio
import hashlib
import json as _json
import logging
import time
from collections.abc import AsyncIterator
from datetime import UTC, datetime, timedelta
from typing import Any

import asyncpg
from fastapi import (
    APIRouter,
    Depends,
    HTTPException,
    Path,
    Query,
    Request,
    Response,
    status,
)
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from .access import (
    access_of,
    can_read,
    guard_access_change,
    guard_owner_only_fields,
    require,
)
from .accessaudit import AccessAction, ExportFormat, record_access
from .auth import Identity, identity_from_request
from .config import Settings
from .db import Database
from .emergency import EmergencyAudit, Use
from .events import (
    LOG_APPENDED,
    PROJECT_CREATED,
    PROJECT_DELETED,
    PROJECT_UPDATED,
    Event,
    EventBroker,
    TooManyStreams,
)
from .merge import MAX_DEPTH as MERGE_MAX_DEPTH
from .merge import TooDeep, merged
from .models import (
    EventDelivery,
    HealthOut,
    HealthStatus,
    LogEntryIn,
    LogEntryOut,
    MeOut,
    PrincipalOut,
    ProjectCreate,
    ProjectOut,
    ProjectPatch,
)
from .principals import MAX_ID_LENGTH, MAX_LOOKUP
from .principals import resolve as resolve_principals
from .securitylog import SecurityEvent, emit
from .signoff import attribute_signoffs

log = logging.getLogger("chai.routes")


router = APIRouter(prefix="/api")

# The app's newId() produces "p" + base36 time + 5 random chars. Imported or
# hand-made ids are also allowed, within reason: this keeps a path segment from
# carrying a slash, a dot-dot, or four kilobytes.
ProjectId = Path(
    ...,
    min_length=1,
    max_length=64,
    pattern=r"^[A-Za-z0-9_.:-]+$",
    description="Project id, as generated by the app's newId().",
)


# --- dependencies -----------------------------------------------------------


def get_settings(request: Request) -> Settings:
    return request.app.state.settings


def get_db(request: Request) -> Database:
    return request.app.state.db


def get_broker(request: Request) -> EventBroker:
    return request.app.state.broker


def get_emergency(request: Request) -> EmergencyAudit:
    return request.app.state.emergency


async def get_identity(
    request: Request, settings: Settings = Depends(get_settings)
) -> Identity:
    """The authenticated caller. Raises 401/403; never returns a guess.

    Also remembers who they are (name and email, as the proxy asserted), so an
    access list or a sign-off can show a person and not an opaque id (#39). That is
    throttled and can never fail the request.
    """
    identity = identity_from_request(request, settings)
    recorder = getattr(request.app.state, "principals", None)
    if recorder is not None:
        await recorder.touch(identity)
    return identity


def _now_iso() -> str:
    return datetime.now(UTC).isoformat(timespec="milliseconds")


def _audience(doc: dict[str, Any], settings: Settings) -> frozenset[str] | None:
    """Who may be told that this project changed.

    ``None`` means everyone, which is correct in exactly two cases: identity
    is disabled, so there is nobody to check a list against; or the project is
    unclaimed, which access.py already treats as unrestricted. Otherwise it is
    the union of the three role lists -- the same set ``can_read`` would admit.
    """
    if not settings.require_identity:
        return None
    access = access_of(doc)
    everyone = access["owners"] + access["writers"] + access["readers"]
    if not access["owners"]:
        return None  # unclaimed: unrestricted, per access.py
    return frozenset(everyone)


# --- health and identity ----------------------------------------------------


@router.get("/health", response_model=HealthOut, tags=["meta"])
async def health(
    response: Response,
    request: Request,
    settings: Settings = Depends(get_settings),
    db: Database = Depends(get_db),
    broker: EventBroker = Depends(get_broker),
) -> HealthOut:
    """Liveness and readiness. **Deliberately unauthenticated.**

    Every platform in ``docs/deploy.md`` health-checks this from inside the
    load balancer, where no identity header exists yet. It returns nothing
    about any project, any user, or the database's address.

    The database check is cached for a couple of seconds. Being both
    unauthenticated and exempt from the rate limiter, an uncached one let
    anyone who could reach the port pull a connection from a pool of ten as
    fast as they liked. See :meth:`Database.ping_cached`.

    The status code follows the database. Every probe this stack is deployed
    behind (docker's HEALTHCHECK, the ALB target group, Cloud Run, Container
    Apps) reads the code and ignores the body, so a 200 with ``"database":
    "down"`` kept a replica with no database in rotation and showed it as
    healthy (#46). A 503 takes it out of rotation, and the dashboard's boot
    probe reads it as a server error and says so rather than opening a
    workspace that fails on first use.
    """
    database_up = await db.ping_cached()
    if not database_up:
        response.status_code = status.HTTP_503_SERVICE_UNAVAILABLE
    return HealthOut(
        status=HealthStatus.OK if database_up else HealthStatus.UNAVAILABLE,
        events=EventDelivery.LOCAL_ONLY if broker.local_only else EventDelivery.LIVE,
        version=settings.version,
        database="up" if database_up else "down",
        db_role=request.app.state.db_role,
        idle_lock_minutes=settings.idle_lock_minutes,
        sign_out_url=settings.sign_out_url,
        auth_mode=settings.auth_mode,
    )


@router.get("/principals", response_model=list[PrincipalOut], tags=["meta"])
async def principals(
    ids: str = Query(
        min_length=1,
        description=f"Comma-separated identity ids, at most {MAX_LOOKUP}.",
    ),
    db: Database = Depends(get_db),
    identity: Identity = Depends(get_identity),
    settings: Settings = Depends(get_settings),
) -> list[PrincipalOut]:
    """Names and emails for identity ids, for the ids the caller may learn.

    An access list, a sign-off and the log hold ids, and an id means nothing to a
    reviewer. This answers for the caller themself and for anyone named on a
    project the caller can read. It does NOT answer for anyone else, however the id
    was obtained, because the table behind it is a staff directory. An id it will
    not or cannot resolve is simply omitted; that is not an error.
    """
    wanted = list(dict.fromkeys(i.strip() for i in ids.split(",") if i.strip()))
    if not wanted:
        raise HTTPException(422, "ids is empty")
    if len(wanted) > MAX_LOOKUP:
        raise HTTPException(422, f"at most {MAX_LOOKUP} ids per request")
    if any(len(i) > MAX_ID_LENGTH for i in wanted):
        raise HTTPException(422, "an id is implausibly long")
    async with db.acquire() as conn:
        rows = await resolve_principals(
            conn, identity.id, wanted, enforced=settings.require_identity
        )
    return [PrincipalOut(id=r["id"], name=r["name"], email=r["email"]) for r in rows]


@router.get("/me", response_model=MeOut, tags=["meta"])
async def me(identity: Identity = Depends(get_identity)) -> MeOut:
    """Who the proxy says you are. The browser shows this as "you"."""
    return MeOut(
        id=identity.id, name=identity.name, email=identity.email, dev=identity.dev
    )


# --- projects ---------------------------------------------------------------


@router.get("/projects", response_model=list[ProjectOut], tags=["projects"])
async def list_projects(
    request: Request,
    db: Database = Depends(get_db),
    identity: Identity = Depends(get_identity),
    emergency: EmergencyAudit = Depends(get_emergency),
    settings: Settings = Depends(get_settings),
) -> list[ProjectOut]:
    """Every project, as ``{id, ...document}``.

    There is no pagination and no per-user filter, because the app's dashboard
    is the whole portfolio and ``subscribeAll`` means all. A governance
    portfolio is tens of projects, not millions.
    """
    enforced = settings.require_identity
    # One transaction with its record (#33): there is no list without a row saying
    # who was given which projects, and a list that cannot be recorded is not served.
    async with db.acquire() as conn, conn.transaction():
        rows = await conn.fetch(
            "SELECT id, doc FROM projects ORDER BY updated_at DESC, id ASC"
        )
        visible = [
            row
            for row in rows
            if can_read(
                row["doc"] or {},
                identity.id,
                enforced=enforced,
                emergency=identity.emergency,
            )
        ]
        await record_access(
            conn,
            identity,
            AccessAction.LIST,
            request,
            detail={
                "count": len(visible),
                "projects": [row["id"] for row in visible],
            },
        )
    if identity.emergency:
        # The projects this list shows only because of emergency access, counted
        # against what the project's own access lists would have shown.
        ordinary = sum(
            1
            for row in visible
            if can_read(row["doc"] or {}, identity.id, enforced=enforced)
        )
        emergency.note_listing(identity, len(visible) - ordinary)
    return [ProjectOut.from_row(row["id"], row["doc"] or {}) for row in visible]


def _listed_ids(value: Any) -> list[str]:
    """A client-supplied access list as unique strings, order kept."""
    if not isinstance(value, list):
        return []
    return list(dict.fromkeys(str(v) for v in value))


@router.post(
    "/projects/{project_id}",
    response_model=ProjectOut,
    status_code=status.HTTP_201_CREATED,
    tags=["projects"],
)
async def create_project(
    body: ProjectCreate,
    project_id: str = ProjectId,
    db: Database = Depends(get_db),
    broker: EventBroker = Depends(get_broker),
    identity: Identity = Depends(get_identity),
    settings: Settings = Depends(get_settings),
) -> ProjectOut:
    """Create a project. 409 if the id is taken.

    ``INSERT ... ON CONFLICT DO NOTHING RETURNING id`` rather than
    "check, then insert": the check-then-insert version has a window in which
    two callers both see no row and the second gets a constraint error instead
    of a clean 409.
    """
    # Sign-offs are attributed to whoever is calling, never to a name the client
    # supplied (#31). Applies to a project created already carrying them too.
    doc = attribute_signoffs(
        dict(body.root),
        None,
        identity.id,
        _now_iso(),
        enforced=settings.require_identity,
    )
    access = doc.get("access") if isinstance(doc.get("access"), dict) else {}
    # Whoever creates a project owns it, whatever the body says. Two things used
    # to be possible when the client's `owners` was kept verbatim (#44): naming
    # only a colleague, which attributes a record to someone who never made it
    # and leaves its creator with no access; and mistyping an address, which
    # orphans the record at birth. The creator is always listed, first, and any
    # other owner the client named is kept, so "create and share" still works.
    # (A project with no owner at all would be "unclaimed", i.e. unrestricted.)
    if settings.require_identity and identity.id:
        named = _listed_ids(access.get("owners"))
        doc["access"] = {
            "owners": [identity.id, *(o for o in named if o != identity.id)],
            "writers": _listed_ids(access.get("writers")),
            "readers": _listed_ids(access.get("readers")),
        }
    async with db.acquire() as conn, conn.transaction():
        row = await conn.fetchrow(
            """
                INSERT INTO projects (id, doc, created_by, updated_by)
                VALUES ($1, $2, $3, $3)
                ON CONFLICT (id) DO NOTHING
                RETURNING id, incarnation
                """,
            project_id,
            doc,
            identity.id,
        )
        if row is None:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=f"Project {project_id!r} already exists.",
            )
        await _snapshot(conn, project_id, row["incarnation"], 1, doc, identity.id)
        await broker.publish(
            Event(PROJECT_CREATED, project_id, audience=_audience(doc, settings)),
            conn,
        )
    emit(
        SecurityEvent.PROJECT_CREATED,
        f"project {project_id} created by {identity.id}",
        level=logging.INFO,
        actor=identity.id,
        project=project_id,
    )
    return ProjectOut.from_row(project_id, doc)


@router.patch("/projects/{project_id}", response_model=ProjectOut, tags=["projects"])
async def patch_project(
    body: ProjectPatch,
    project_id: str = ProjectId,
    db: Database = Depends(get_db),
    broker: EventBroker = Depends(get_broker),
    identity: Identity = Depends(get_identity),
    emergency: EmergencyAudit = Depends(get_emergency),
    settings: Settings = Depends(get_settings),
) -> ProjectOut:
    """Deep-merge the body into the stored document.

    **Atomicity.** The merge is a read-modify-write in Python, held inside a
    transaction by ``SELECT ... FOR UPDATE``. The row lock is what makes two
    concurrent PATCHes to different fields safe: the second one blocks at the
    ``SELECT`` until the first commits, then reads the *committed* document and
    merges onto it. Neither write is lost.

    The alternative -- a recursive ``jsonb`` merge in PL/pgSQL -- would also be
    atomic, and was rejected for one reason: it would be a *second*
    implementation of a merge rule whose exact semantics (arrays replace, null
    replaces, type change replaces) the browser already defines in
    ``app/js/00-core/00-util.js``. Two implementations drift; one does not. See
    ``app/merge.py``.

    Note that PostgreSQL's ``||`` operator is not an option at all: it merges
    only the top level, so ``{"items": {"s4-2": {...}}}`` would discard every
    other key under ``items``.
    """
    patch = body.root
    async with db.acquire() as conn, conn.transaction():
        row = await conn.fetchrow(
            "SELECT doc, incarnation FROM projects WHERE id = $1 FOR UPDATE",
            project_id,
        )
        if row is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"No project {project_id!r}.",
            )
        before = row["doc"] or {}
        enforced = settings.require_identity
        used_emergency = require(
            before,
            identity.id,
            "write",
            enforced=enforced,
            project_id=project_id,
            emergency=identity.emergency,
        )
        guard_access_change(
            before,
            patch,
            identity.id,
            enforced=enforced,
            project_id=project_id,
            emergency=identity.emergency,
        )
        guard_owner_only_fields(
            before,
            patch,
            identity.id,
            enforced=enforced,
            project_id=project_id,
            emergency=identity.emergency,
        )
        if used_emergency:
            await emergency.record(
                conn, identity, project_id, "change this project", Use.WRITE
            )
        # Who signed, and when, is the server's to say (#31). After the guards,
        # so an unauthorized caller is refused before anything is rewritten.
        patch = attribute_signoffs(
            patch, before, identity.id, _now_iso(), enforced=enforced
        )
        try:
            document = merged(before, patch)
        except TooDeep as exc:
            raise HTTPException(status.HTTP_400_BAD_REQUEST, str(exc)) from exc
        rev = await conn.fetchval(
            """
                UPDATE projects
                   SET doc = $2, rev = rev + 1, updated_at = now(), updated_by = $3
                 WHERE id = $1
             RETURNING rev
                """,
            project_id,
            document,
            identity.id,
        )
        await _snapshot(
            conn, project_id, row["incarnation"], rev, document, identity.id
        )
        await broker.publish(
            Event(
                PROJECT_UPDATED,
                project_id,
                audience=_audience(document, settings),
            ),
            conn,
        )
    return ProjectOut.from_row(project_id, document)


@router.delete(
    "/projects/{project_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    tags=["projects"],
)
async def delete_project(
    project_id: str = ProjectId,
    db: Database = Depends(get_db),
    broker: EventBroker = Depends(get_broker),
    identity: Identity = Depends(get_identity),
    emergency: EmergencyAudit = Depends(get_emergency),
    settings: Settings = Depends(get_settings),
) -> Response:
    """Delete the live project and its audit log. It does NOT erase the history.

    The log goes with it by ``ON DELETE CASCADE``. That is the only way log
    rows are ever removed -- there is no endpoint that deletes an entry.

    Every revision's full document is KEPT in ``project_version``, on purpose: an
    audit trail that vanishes with its subject is not one. So deleting is not
    erasure. ``DELETE .../versions`` is the second, separate step that destroys
    the history (#36).

    What deletion leaves behind is written here, in the same transaction, to
    ``project_deletion``: who deleted it, when, and what its last revision hashed
    to. Before this the only record was a line on container stdout.
    """
    async with db.acquire() as conn, conn.transaction():
        current = await conn.fetchrow(
            "SELECT doc FROM projects WHERE id = $1 FOR UPDATE", project_id
        )
        if current is not None:
            if require(
                current["doc"] or {},
                identity.id,
                "own",
                enforced=settings.require_identity,
                project_id=project_id,
                emergency=identity.emergency,
            ):
                await emergency.record(
                    conn, identity, project_id, "delete this project", Use.DELETE
                )
            # The tombstone is written AFTER the access check and BEFORE the
            # delete, from the same row lock, so a refused or failed delete
            # leaves nothing behind and a successful one cannot lose it.
            await conn.execute(
                """
                INSERT INTO project_deletion
                       (project_id, incarnation, deleted_by, last_rev, last_md5)
                SELECT p.id, p.incarnation, $2, p.rev, v.content_md5
                  FROM projects p
                  LEFT JOIN project_version v
                         ON v.project_id = p.id
                        AND v.incarnation = p.incarnation
                        AND v.rev = p.rev
                 WHERE p.id = $1
                """,
                project_id,
                identity.id,
            )
        row = await conn.fetchrow(
            "DELETE FROM projects WHERE id = $1 RETURNING id", project_id
        )
        if row is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"No project {project_id!r}.",
            )
        # The audience comes from the document as it was BEFORE the delete:
        # afterwards there is no access list to read, and defaulting to
        # "everyone" at that point would announce the deletion of a record
        # most subscribers were never allowed to know about.
        await broker.publish(
            Event(
                PROJECT_DELETED,
                project_id,
                audience=_audience(current["doc"] or {}, settings)
                if current is not None
                else None,
            ),
            conn,
        )
    emit(
        SecurityEvent.PROJECT_DELETED,
        f"project {project_id} deleted by {identity.id}",
        level=logging.INFO,
        actor=identity.id,
        project=project_id,
    )
    return Response(status_code=status.HTTP_204_NO_CONTENT)


# --- version history --------------------------------------------------------

# Excluded from the fingerprint. Must match CANON_SKIP in
# app/js/00-core/12-hash.js, or the browser and the server will disagree about
# what the same record hashes to -- which is worse than having no hash, because
# it looks like evidence of a change that did not happen.
_HASH_SKIP = frozenset(
    {"updatedAt", "updatedBy", "cardUpdatedAt", "_state", "contentHash", "generated"}
)


def _canonical(value: Any, _depth: int = 0) -> Any:
    """Deterministic shape: keys sorted at every depth, volatile keys dropped.

    Bounded for the same reason deep_merge is: this runs on every write, and
    a RecursionError here would fail the snapshot of a document the caller
    had already been told was accepted.
    """
    if _depth > MERGE_MAX_DEPTH:
        raise TooDeep(f"document nests deeper than {MERGE_MAX_DEPTH} levels")
    if isinstance(value, dict):
        return {
            k: _canonical(v, _depth + 1)
            for k, v in sorted(value.items())
            if k not in _HASH_SKIP
        }
    if isinstance(value, list):
        return [_canonical(v, _depth + 1) for v in value]
    return value


def content_md5(doc: dict[str, Any]) -> str:
    """The same fingerprint the browser computes, over the same canonical form.

    MD5 because that is what the record is labeled with; it answers "is this
    the same version?" and nothing stronger. It is not a tamper seal, and
    anything that presents it as one is wrong -- see the note in the app's
    changelog view.
    """
    canon = _json.dumps(
        _canonical(doc), sort_keys=True, separators=(",", ":"), ensure_ascii=False
    )
    return hashlib.md5(canon.encode("utf-8")).hexdigest()


async def _snapshot(
    conn: Any,
    project_id: str,
    incarnation: Any,
    rev: int,
    doc: dict[str, Any],
    by: str | None,
) -> None:
    """Record one immutable version. Caller supplies the open transaction.

    The access list is copied onto the row. That is what keeps history as
    restricted as the record was: a deleted project has no live document to
    check against, and without this its snapshots were readable by anyone who
    could reach the API. See ``003_version_access.sql``.
    """
    access = doc.get("access") if isinstance(doc.get("access"), dict) else {}
    # No ON CONFLICT. A conflict here means two snapshots claim the same
    # (project, incarnation, revision), which cannot happen while the caller
    # holds the row lock -- so if it does, something is wrong and the write
    # should fail loudly. The previous DO NOTHING silently dropped the rev 1 of
    # a project that reused a deleted id, leaving a history with a missing
    # first revision and no indication of it.
    await conn.execute(
        """
        INSERT INTO project_version
               (project_id, incarnation, rev, doc, content_md5, changed_by, access)
        VALUES ($1, $2, $3, $4, $5, $6, $7)
        """,
        project_id,
        incarnation,
        rev,
        doc,
        content_md5(doc),
        by,
        access,
    )


async def _version_gate(
    conn: Any, project_id: str
) -> tuple[dict[str, Any], Any] | None:
    """Which history to read, and the access list that governs reading it.

    Returns ``(doc_for_access_check, incarnation)``, or ``None`` when there is
    no history at all -- which the caller turns into a 404.

    The incarnation matters as much as the access list. Project ids are
    caller-chosen and snapshots outlive their project, so one id can have two
    unrelated histories: the deleted project's, and the one someone created
    afterwards reusing the id. Reads are scoped to the LIVE project's
    incarnation when there is one, and to the most recent incarnation
    otherwise, so a reused id never shows two records merged into one.

    Access comes from the live project where there is one, and otherwise from
    the access list recorded on that incarnation's most recent snapshot -- so
    deleting a project does not turn its history into a public record.
    """
    live = await conn.fetchrow(
        "SELECT doc, incarnation FROM projects WHERE id = $1", project_id
    )
    if live is not None:
        return (live["doc"] or {}), live["incarnation"]
    row = await conn.fetchrow(
        """
        SELECT access, incarnation FROM project_version
         WHERE project_id = $1
         ORDER BY changed_at DESC, rev DESC
         LIMIT 1
        """,
        project_id,
    )
    if row is None:
        return None
    return {"access": row["access"] or {}}, row["incarnation"]


# --- version history --------------------------------------------------------


@router.get("/projects/{project_id}/versions", tags=["versions"])
async def list_versions(
    request: Request,
    project_id: str = ProjectId,
    db: Database = Depends(get_db),
    settings: Settings = Depends(get_settings),
    identity: Identity = Depends(get_identity),
    emergency: EmergencyAudit = Depends(get_emergency),
) -> list[dict[str, Any]]:
    """Every recorded revision of this project, newest first.

    Metadata only -- revision, fingerprint, who, when. The documents
    themselves are fetched one at a time, because returning fifty full
    snapshots to render a list is a lot of bytes for a column of dates.

    Access is checked against the live project, or -- when it has been deleted
    -- against the access list recorded on its most recent snapshot. A deleted
    project keeps its versions on purpose (see 002_versions.sql), and it must
    not become readable to everyone in the process: "it was deleted, and here
    is what it said" is the audit answer for the people who could read it, not
    for everybody with an account.
    """
    async with db.acquire() as conn, conn.transaction():
        gate = await _version_gate(conn, project_id)
        if gate is None:
            raise HTTPException(status.HTTP_404_NOT_FOUND, "No such project")
        doc, incarnation = gate
        if require(
            doc,
            identity.id,
            "read",
            enforced=settings.require_identity,
            project_id=project_id,
            emergency=identity.emergency,
        ):
            await emergency.record(
                conn, identity, project_id, "read this project's history", Use.READ
            )
        await record_access(
            conn,
            identity,
            AccessAction.READ_VERSIONS,
            request,
            project_id=project_id,
        )
        rows = await conn.fetch(
            """
            SELECT rev, content_md5, changed_by, changed_at, purged_at, purged_by
              FROM project_version
             WHERE project_id = $1 AND incarnation = $2
             ORDER BY rev DESC
            """,
            project_id,
            incarnation,
        )
    return [
        {
            "rev": r["rev"],
            "md5": r["content_md5"],
            "by": r["changed_by"],
            "at": r["changed_at"].isoformat(),
            "purged": r["purged_at"] is not None,
            **(
                {
                    "purgedAt": r["purged_at"].isoformat(),
                    "purgedBy": r["purged_by"],
                }
                if r["purged_at"] is not None
                else {}
            ),
        }
        for r in rows
    ]


@router.get("/projects/{project_id}/versions/{rev}", tags=["versions"])
async def read_version(
    request: Request,
    project_id: str = ProjectId,
    rev: int = 0,
    db: Database = Depends(get_db),
    settings: Settings = Depends(get_settings),
    identity: Identity = Depends(get_identity),
    emergency: EmergencyAudit = Depends(get_emergency),
) -> dict[str, Any]:
    """One revision, exactly as it was stored, with its fingerprint.

    A purged revision returns an empty ``doc`` and ``purged: true``. Its
    ``md5`` is the fingerprint of the ORIGINAL content, which is what makes the
    tombstone evidence rather than a gap.
    """
    async with db.acquire() as conn, conn.transaction():
        gate = await _version_gate(conn, project_id)
        if gate is None:
            raise HTTPException(status.HTTP_404_NOT_FOUND, "No such project")
        doc, incarnation = gate
        if require(
            doc,
            identity.id,
            "read",
            enforced=settings.require_identity,
            project_id=project_id,
            emergency=identity.emergency,
        ):
            await emergency.record(
                conn, identity, project_id, "read this project's history", Use.READ
            )
        row = await conn.fetchrow(
            """
            SELECT rev, doc, content_md5, changed_by, changed_at, purged_at, purged_by
              FROM project_version
             WHERE project_id = $1 AND incarnation = $2 AND rev = $3
            """,
            project_id,
            incarnation,
            rev,
        )
        if row is None:
            raise HTTPException(
                status.HTTP_404_NOT_FOUND, f"No revision {rev} of {project_id!r}."
            )
        # Only a revision that exists and is returned is a read of it.
        await record_access(
            conn,
            identity,
            AccessAction.READ_VERSION,
            request,
            project_id=project_id,
            revision=row["rev"],
        )
    out: dict[str, Any] = {
        "rev": row["rev"],
        "md5": row["content_md5"],
        "by": row["changed_by"],
        "at": row["changed_at"].isoformat(),
        "doc": row["doc"],
        "purged": row["purged_at"] is not None,
    }
    if row["purged_at"] is not None:
        out["purgedAt"] = row["purged_at"].isoformat()
        out["purgedBy"] = row["purged_by"]
    return out


@router.delete(
    "/projects/{project_id}/versions",
    status_code=status.HTTP_204_NO_CONTENT,
    tags=["versions"],
)
async def purge_versions(
    project_id: str = ProjectId,
    db: Database = Depends(get_db),
    broker: EventBroker = Depends(get_broker),
    settings: Settings = Depends(get_settings),
    identity: Identity = Depends(get_identity),
    emergency: EmergencyAudit = Depends(get_emergency),
) -> Response:
    """Destroy the stored content of every retained revision. Owner only.

    This is the disposal path. Snapshots are otherwise append-only and survive
    the project's deletion, which is right for an audit trail and wrong as an
    absolute: data entered in error -- a patient identifier pasted into an
    evidence field -- has to be removable, and before this it was not
    removable through the application at all.

    What survives is deliberate. Each row keeps its revision number, its
    author, its timestamp and its ORIGINAL ``content_md5``; only ``doc`` is
    emptied, and ``purged_at``/``purged_by`` record who did it. A row that
    vanished would be indistinguishable from a snapshot never taken. A trigger
    in 003_version_access.sql permits exactly this transition and nothing else.

    It also redacts the project's AUDIT LOG, in the same transaction. The client
    writes each entry's prose with the values in it ("Changed evidence: “old” ->
    “new”") as well as ``change.from`` and ``change.to``, and may add any other
    field it likes, so emptying the snapshots alone left the same identifier
    readable in a second table (#36). The redaction is a whitelist defined once, in
    SQL (``project_log_redacted``), and a trigger permits an UPDATE only if it
    produces exactly that. The purge is then recorded in the log by the server.

    Works on a deleted project, whose access list comes from its last snapshot
    -- otherwise the one record most likely to need purging would be the one
    record nobody could purge. (A deleted project's log is already gone with it.)
    """
    async with db.acquire() as conn, conn.transaction():
        # Serialize with a concurrent patch or delete of the live project, if any.
        live = await conn.fetchval(
            "SELECT id FROM projects WHERE id = $1 FOR UPDATE", project_id
        )
        gate = await _version_gate(conn, project_id)
        if gate is None:
            raise HTTPException(status.HTTP_404_NOT_FOUND, "No such project")
        doc, incarnation = gate
        if require(
            doc,
            identity.id,
            "own",
            enforced=settings.require_identity,
            project_id=project_id,
            emergency=identity.emergency,
        ):
            await emergency.record(
                conn,
                identity,
                project_id,
                "destroy this project's history",
                Use.WRITE,
            )
        # One timestamp for the whole purge, so the rows it touches, its log entry
        # and its security event all name the same moment, and a restore can find
        # and re-apply it (scripts/purge_ledger.py, #116).
        now = datetime.now(UTC)
        purged, through_rev = await conn.fetchrow(
            """
            WITH redacted AS (
                UPDATE project_version
                   SET doc = '{}'::jsonb, purged_at = $4, purged_by = $3
                 WHERE project_id = $1
                   AND incarnation = $2
                   AND purged_at IS NULL
             RETURNING rev
            )
            SELECT count(*), max(rev) FROM redacted
            """,
            project_id,
            incarnation,
            identity.id,
            now,
        )
        entries, through_seq = 0, None
        if live is not None:
            entries, through_seq = await conn.fetchrow(
                """
                WITH redacted AS (
                    UPDATE project_log
                       SET entry = project_log_redacted(entry),
                           purged_at = $3,
                           purged_by = $2
                     WHERE project_id = $1
                       AND purged_at IS NULL
                       AND NOT is_system
                 RETURNING seq
                )
                SELECT count(*), max(seq) FROM redacted
                """,
                project_id,
                identity.id,
                now,
            )
            if purged or entries:
                # The server records that it happened. is_system is a column the
                # client cannot set, so this entry can be neither forged nor redacted.
                plural = "entry" if entries == 1 else "entries"
                await conn.execute(
                    """
                    INSERT INTO project_log (project_id, at, by_id, entry, is_system)
                    VALUES ($1, $2, $3, $4, true)
                    """,
                    project_id,
                    now,
                    identity.id,
                    {
                        "text": (
                            f"Purged: the content of {purged or 0} revision(s) and "
                            f"{entries} audit-log {plural} was destroyed."
                        ),
                        "at": now.isoformat(timespec="milliseconds"),
                        "by": identity.id,
                    },
                )
                await broker.publish(
                    Event(
                        LOG_APPENDED,
                        project_id,
                        audience=_audience(doc, settings),
                    ),
                    conn,
                )
    emit(
        SecurityEvent.VERSIONS_PURGED,
        f"version history of {project_id} purged by {identity.id} "
        f"({purged or 0} revision(s), {entries or 0} log entries)",
        actor=identity.id,
        project=project_id,
        revisions=purged or 0,
        log_entries=entries or 0,
        # Enough to re-apply this purge to a database restored from an older dump,
        # from the security log alone, when the live database is gone (#116).
        incarnation=str(incarnation),
        purged_at=now.isoformat(),
        through_rev=through_rev,
        through_seq=through_seq,
    )
    return Response(status_code=status.HTTP_204_NO_CONTENT)


# --- audit log --------------------------------------------------------------


# The largest page a caller may ask for. A project's whole history is paged, not
# fetched in one go, so no request can make the server build an unbounded list.
LOG_MAX_PAGE = 500


_EPOCH = datetime(1970, 1, 1, tzinfo=UTC)


def _log_cursor(at: datetime, seq: int) -> str:
    """``<microseconds since epoch>.<seq>``: opaque, exact, and safe in a URL.

    An ISO timestamp as a cursor carries ``+`` and ``:``, and a query string turns
    ``+`` into a space, so a client that forgot to encode it broke silently.
    """
    return f"{(at - _EPOCH) // timedelta(microseconds=1)}.{seq}"


def _parse_log_cursor(raw: str | None) -> tuple[datetime | None, int | None]:
    """An ``X-Log-Next`` cursor, or (None, None) for the first page."""
    if raw is None:
        return None, None
    try:
        micros, dot, seq = raw.partition(".")
        if not dot:
            raise ValueError("no separator")
        return _EPOCH + timedelta(microseconds=int(micros)), int(seq)
    except (ValueError, OverflowError) as exc:
        raise HTTPException(
            status.HTTP_400_BAD_REQUEST,
            "before must be an X-Log-Next cursor from a previous page.",
        ) from exc


@router.get(
    "/projects/{project_id}/log",
    response_model=list[LogEntryOut],
    tags=["audit log"],
)
async def read_log(
    response: Response,
    request: Request,
    project_id: str = ProjectId,
    limit: int | None = Query(
        default=None,
        ge=1,
        description=(
            "Entries per page. Default is the server's page size; "
            f"capped at {LOG_MAX_PAGE}."
        ),
    ),
    before: str | None = Query(
        default=None,
        description="Cursor from a previous page's X-Log-Next: only older entries.",
    ),
    db: Database = Depends(get_db),
    settings: Settings = Depends(get_settings),
    identity: Identity = Depends(get_identity),
    emergency: EmergencyAudit = Depends(get_emergency),
) -> list[LogEntryOut]:
    """One page of the audit log, newest first -- what ``subscribeLog`` shows.

    The default page is the newest ``LOG_PAGE_SIZE`` (60). It used to be the only
    page: there was no way to ask for anything older, so entry 61 onward was
    unreachable through the API and every export carried the window silently
    (#40). Now:

    * ``X-Log-Total`` is the number of entries the project has, so a caller can
      say "showing 60 of 412" instead of passing a window off as the history;
    * ``X-Log-Next`` is a cursor, present only when there is more. Pass it as
      ``?before=`` for the next page. It is ``(at, seq)``, which the existing
      index ``(project_id, at DESC, seq DESC)`` serves exactly, and ``seq`` breaks
      ties so two entries in the same microsecond neither repeat nor vanish.

    A missing project returns an empty list rather than 404. The app subscribes
    to a log and deletes a project from two different code paths, and a 404
    racing a delete would surface as an error toast for something the user just
    did on purpose.
    """
    page = min(limit or settings.log_page_size, LOG_MAX_PAGE)
    cursor_at, cursor_seq = _parse_log_cursor(before)
    async with db.acquire() as conn, conn.transaction():
        # The log is the project's history; seeing it is seeing the project.
        # A missing project still returns an empty list rather than 404 -- see
        # the docstring -- so an absent row is not an access failure.
        owner_row = await conn.fetchrow(
            "SELECT doc FROM projects WHERE id = $1", project_id
        )
        if owner_row is not None:
            if require(
                owner_row["doc"] or {},
                identity.id,
                "read",
                enforced=settings.require_identity,
                project_id=project_id,
                emergency=identity.emergency,
            ):
                await emergency.record(
                    conn, identity, project_id, "read this project's log", Use.READ
                )
            # A missing project discloses nothing, so there is nothing to record.
            await record_access(
                conn,
                identity,
                AccessAction.READ_LOG,
                request,
                project_id=project_id,
            )
        rows = await conn.fetch(
            """
            SELECT seq, at, entry, purged_at FROM project_log
             WHERE project_id = $1
               AND ($2::timestamptz IS NULL OR (at, seq) < ($2, $3))
             ORDER BY at DESC, seq DESC
             LIMIT $4
            """,
            project_id,
            cursor_at,
            cursor_seq,
            page + 1,  # one extra, to know whether there is another page
        )
        total = await conn.fetchval(
            "SELECT count(*) FROM project_log WHERE project_id = $1", project_id
        )
    response.headers["X-Log-Total"] = str(total)
    if len(rows) > page:
        rows = rows[:page]
        last = rows[-1]
        response.headers["X-Log-Next"] = _log_cursor(last["at"], last["seq"])
    # `purged` comes from a column the client cannot set, never from the entry.
    return [
        LogEntryOut(
            **{**row["entry"], **({"purged": True} if row["purged_at"] else {})}
        )
        for row in rows
    ]


@router.post(
    "/projects/{project_id}/log",
    response_model=LogEntryOut,
    status_code=status.HTTP_201_CREATED,
    tags=["audit log"],
)
async def append_log(
    body: LogEntryIn,
    project_id: str = ProjectId,
    db: Database = Depends(get_db),
    broker: EventBroker = Depends(get_broker),
    identity: Identity = Depends(get_identity),
    emergency: EmergencyAudit = Depends(get_emergency),
    settings: Settings = Depends(get_settings),
) -> LogEntryOut:
    """Append one entry. There is no update and no delete, by design.

    ``at`` and ``by`` are **overwritten** here, with the server clock and the
    proxy identity, even though the browser sends both. An audit log whose
    author and timestamp come from the client is not an audit log -- it is a
    field the client can set. A trigger in ``001_init.sql`` blocks ``UPDATE``
    on this table so a later bug cannot rewrite history either.
    """
    entry: dict[str, Any] = body.model_dump()
    now = datetime.now(UTC)
    entry["at"] = now.isoformat(timespec="milliseconds")
    entry["by"] = identity.id

    async with db.acquire() as conn, conn.transaction():
        target = await conn.fetchrow(
            "SELECT doc FROM projects WHERE id = $1", project_id
        )
        if target is not None and require(
            target["doc"] or {},
            identity.id,
            "write",
            enforced=settings.require_identity,
            project_id=project_id,
            emergency=identity.emergency,
        ):
            await emergency.record(
                conn, identity, project_id, "add to this project's log", Use.WRITE
            )
        try:
            await conn.execute(
                """
                    INSERT INTO project_log (project_id, at, by_id, entry)
                    VALUES ($1, $2, $3, $4)
                    """,
                project_id,
                now,
                identity.id,
                entry,
            )
        except asyncpg.ForeignKeyViolationError as exc:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"No project {project_id!r}.",
            ) from exc
        await broker.publish(
            Event(
                LOG_APPENDED,
                project_id,
                audience=_audience(
                    (target["doc"] or {}) if target is not None else {}, settings
                ),
            ),
            conn,
        )
    return LogEntryOut(**entry)


# --- exports ----------------------------------------------------------------


class ExportBeacon(BaseModel):
    """What the dashboard reports when it produces a download."""

    format: ExportFormat


@router.post(
    "/projects/{project_id}/exports",
    status_code=status.HTTP_204_NO_CONTENT,
    tags=["audit log"],
)
async def record_export(
    body: ExportBeacon,
    request: Request,
    project_id: str = ProjectId,
    db: Database = Depends(get_db),
    settings: Settings = Depends(get_settings),
    identity: Identity = Depends(get_identity),
    emergency: EmergencyAudit = Depends(get_emergency),
) -> Response:
    """The dashboard reports that it produced an export of this project.

    Exports are built in the browser from data it already fetched, so the server never
    sees one happen. This is the record of ordinary use: it is NOT a control, because a
    client can omit it. What bounds what any export could contain is the reads that
    fetched the data, which are recorded. A caller needs read access to the project,
    so it cannot be used to probe for projects or to write entries about ones you
    cannot see.
    """
    if body.format is ExportFormat.CSV:
        raise HTTPException(
            status.HTTP_422_UNPROCESSABLE_ENTITY,
            "csv is a portfolio export; POST /api/exports",
        )
    async with db.acquire() as conn, conn.transaction():
        row = await conn.fetchrow("SELECT doc FROM projects WHERE id = $1", project_id)
        if row is None:
            raise HTTPException(status.HTTP_404_NOT_FOUND, "No such project")
        if require(
            row["doc"] or {},
            identity.id,
            "read",
            enforced=settings.require_identity,
            project_id=project_id,
            emergency=identity.emergency,
        ):
            await emergency.record(
                conn, identity, project_id, "export this project", Use.READ
            )
        await record_access(
            conn,
            identity,
            AccessAction.EXPORT,
            request,
            project_id=project_id,
            detail={"format": body.format.value},
        )
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@router.post("/exports", status_code=status.HTTP_204_NO_CONTENT, tags=["audit log"])
async def record_portfolio_export(
    body: ExportBeacon,
    request: Request,
    db: Database = Depends(get_db),
    settings: Settings = Depends(get_settings),
    identity: Identity = Depends(get_identity),
) -> Response:
    """The dashboard reports a whole-portfolio export (the CSV)."""
    if body.format is not ExportFormat.CSV:
        raise HTTPException(
            status.HTTP_422_UNPROCESSABLE_ENTITY,
            "only csv is a portfolio export; POST /api/projects/{id}/exports",
        )
    async with db.acquire() as conn, conn.transaction():
        rows = await conn.fetch("SELECT id, doc FROM projects ORDER BY id")
        readable = [
            row["id"]
            for row in rows
            if can_read(
                row["doc"] or {},
                identity.id,
                enforced=settings.require_identity,
                emergency=identity.emergency,
            )
        ]
        await record_access(
            conn,
            identity,
            AccessAction.EXPORT,
            request,
            detail={
                "format": body.format.value,
                "scope": "portfolio",
                "projects": readable,
            },
        )
    return Response(status_code=status.HTTP_204_NO_CONTENT)


# --- change stream ----------------------------------------------------------


@router.get("/events", tags=["events"])
async def events(
    request: Request,
    db: Database = Depends(get_db),
    broker: EventBroker = Depends(get_broker),
    settings: Settings = Depends(get_settings),
    identity: Identity = Depends(get_identity),
) -> StreamingResponse:
    """One ``text/event-stream`` event per change, for as long as you hold it.

    Events carry an id, never a document, so the stream stays well under
    ``NOTIFY``'s 8000-byte payload cap no matter how large a project grows. The
    client refetches what changed.

    **Filtered per subscriber.** A stream only carries changes to projects its
    holder can read. Without that, every authenticated user learned the id and
    the change cadence of every project in the portfolio, including the ones
    ``GET /api/projects`` correctly filtered out of their view.

    The comment heartbeat matters more than it looks: Cloud Run, an ALB and
    Azure Front Door all close an idle connection, and an SSE stream with
    nothing to say is indistinguishable from a dead one until a byte moves.
    """

    # Registered BEFORE the StreamingResponse is built. FastAPI constructs the
    # response eagerly and runs the generator afterwards, so refusing inside
    # the generator would mean sending 200 and then an error body.
    # Who attached is part of the read trail: the stream delivers change
    # notifications (#33). A stream that cannot be recorded is not opened.
    async with db.acquire() as conn:
        await record_access(conn, identity, AccessAction.STREAM_ATTACH, request)
    try:
        subscriber = broker.attach(identity.id)
    except TooManyStreams as exc:
        emit(
            SecurityEvent.STREAM_REFUSED,
            f"refused an event stream: {exc}",
            actor=identity.id,
        )
        raise HTTPException(
            status.HTTP_429_TOO_MANY_REQUESTS,
            "Too many open event streams for this user. Close some tabs.",
        ) from exc

    async def stream() -> AsyncIterator[str]:
        started = time.monotonic()
        lifetime = settings.sse_max_lifetime_seconds
        try:
            # Tell EventSource how long to wait before reconnecting, and send
            # one frame immediately so proxies that buffer until first byte
            # release the response headers.
            yield "retry: 3000\n\n"
            yield Event("hello", None, _now_iso()).sse()
            while True:
                if await request.is_disconnected():
                    return
                # The stream authenticated once, when it attached, so it would
                # keep delivering after the account behind it was disabled (#49).
                # The API cannot ask the identity provider whether the session is
                # still good; it can end the stream, and the browser's reconnect
                # goes back through the front door and is authenticated again.
                remaining = (
                    lifetime - (time.monotonic() - started) if lifetime else None
                )
                if remaining is not None and remaining <= 0:
                    log.info("closing an event stream after %.0fs", lifetime)
                    return
                # Wake for whichever comes first, the heartbeat or the end of the
                # stream's life. Waiting a whole heartbeat would let it live that
                # much longer than the limit says.
                wait = settings.sse_keepalive_seconds
                if remaining is not None:
                    wait = min(wait, remaining)
                try:
                    event = await asyncio.wait_for(subscriber.queue.get(), timeout=wait)
                except TimeoutError:
                    if remaining is None or time.monotonic() - started < lifetime:
                        yield ": ping\n\n"
                    continue
                yield event.sse()
        finally:
            broker.detach(subscriber)

    return StreamingResponse(
        stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache, no-store, no-transform",
            "Connection": "keep-alive",
            # nginx and anything derived from it buffer proxied responses by
            # default, which turns a live stream into a long silence.
            "X-Accel-Buffering": "no",
        },
    )
