"""Every endpoint in the store contract, and nothing else.

The browser persists through six methods. Each maps to one route:

================================  ==========================================
``subscribeAll(cb, err)``         ``GET /api/projects`` + ``GET /api/events``
``create(id, data)``              ``POST /api/projects/{id}``
``update(id, patch)``             ``PATCH /api/projects/{id}``
``remove(id)``                    ``DELETE /api/projects/{id}``
``log(id, entry)``                ``POST /api/projects/{id}/log``
``subscribeLog(id, cb)``          ``GET /api/projects/{id}/log`` + events
================================  ==========================================

The two ``subscribe*`` methods are a fetch plus a stream: the client fetches
once, then holds ``/api/events`` open and refetches whatever an event says
changed.
"""

from __future__ import annotations

import asyncio
import hashlib
import json as _json
import logging
from collections.abc import AsyncIterator
from datetime import UTC, datetime
from typing import Any

import asyncpg
from fastapi import APIRouter, Depends, HTTPException, Path, Request, Response, status
from fastapi.responses import StreamingResponse

from .access import (
    can_read,
    guard_access_change,
    guard_owner_only_fields,
    require,
)
from .auth import Identity, identity_from_request
from .config import Settings
from .db import Database
from .events import (
    LOG_APPENDED,
    PROJECT_CREATED,
    PROJECT_DELETED,
    PROJECT_UPDATED,
    Event,
    EventBroker,
)
from .merge import merged
from .models import (
    HealthOut,
    LogEntryIn,
    LogEntryOut,
    MeOut,
    ProjectCreate,
    ProjectOut,
    ProjectPatch,
)

log = logging.getLogger("chai.routes")

router = APIRouter(prefix="/api")

# The app's newId() produces "p" + base36 time + 5 random chars. Imported or
# hand-made ids are also allowed, within reason: this keeps a path segment from
# carrying a slash, a dot-dot, or four kilobytes.
ProjectId = Path(
    ...,
    min_length=1,
    max_length=64,
    pattern=r"^[A-Za-z0-9_.:-]+$",
    description="Project id, as generated by the app's newId().",
)


# --- dependencies -----------------------------------------------------------


def get_settings(request: Request) -> Settings:
    return request.app.state.settings


def get_db(request: Request) -> Database:
    return request.app.state.db


def get_broker(request: Request) -> EventBroker:
    return request.app.state.broker


def get_identity(
    request: Request, settings: Settings = Depends(get_settings)
) -> Identity:
    """The authenticated caller. Raises 401/403; never returns a guess."""
    return identity_from_request(request, settings)


def _now_iso() -> str:
    return datetime.now(UTC).isoformat(timespec="milliseconds")


# --- health and identity ----------------------------------------------------


@router.get("/health", response_model=HealthOut, tags=["meta"])
async def health(
    settings: Settings = Depends(get_settings), db: Database = Depends(get_db)
) -> HealthOut:
    """Liveness and readiness. **Deliberately unauthenticated.**

    Every platform in ``docs/deploy.md`` health-checks this from inside the
    load balancer, where no identity header exists yet. It returns nothing
    about any project, any user, or the database's address.
    """
    return HealthOut(
        status="ok",
        version=settings.version,
        database="up" if await db.ping() else "down",
        auth_mode=settings.auth_mode,
    )


@router.get("/me", response_model=MeOut, tags=["meta"])
async def me(identity: Identity = Depends(get_identity)) -> MeOut:
    """Who the proxy says you are. The browser shows this as "you"."""
    return MeOut(
        id=identity.id, name=identity.name, email=identity.email, dev=identity.dev
    )


# --- projects ---------------------------------------------------------------


@router.get("/projects", response_model=list[ProjectOut], tags=["projects"])
async def list_projects(
    db: Database = Depends(get_db),
    identity: Identity = Depends(get_identity),
    settings: Settings = Depends(get_settings),
) -> list[ProjectOut]:
    """Every project, as ``{id, ...document}``.

    There is no pagination and no per-user filter, because the app's dashboard
    is the whole portfolio and ``subscribeAll`` means all. A governance
    portfolio is tens of projects, not millions.
    """
    async with db.acquire() as conn:
        rows = await conn.fetch(
            "SELECT id, doc FROM projects ORDER BY updated_at DESC, id ASC"
        )
    enforced = settings.require_identity
    return [
        ProjectOut.from_row(row["id"], row["doc"] or {})
        for row in rows
        if can_read(row["doc"] or {}, identity.id, enforced=enforced)
    ]


@router.post(
    "/projects/{project_id}",
    response_model=ProjectOut,
    status_code=status.HTTP_201_CREATED,
    tags=["projects"],
)
async def create_project(
    body: ProjectCreate,
    project_id: str = ProjectId,
    db: Database = Depends(get_db),
    broker: EventBroker = Depends(get_broker),
    identity: Identity = Depends(get_identity),
    settings: Settings = Depends(get_settings),
) -> ProjectOut:
    """Create a project. 409 if the id is taken.

    ``INSERT ... ON CONFLICT DO NOTHING RETURNING id`` rather than
    "check, then insert": the check-then-insert version has a window in which
    two callers both see no row and the second gets a constraint error instead
    of a clean 409.
    """
    doc = dict(body.root)
    access = doc.get("access") if isinstance(doc.get("access"), dict) else {}
    # Whoever creates a project owns it. A project created with no owner would
    # be "unclaimed", which means unrestricted -- an open record from birth.
    if settings.require_identity and identity.id and not access.get("owners"):
        doc["access"] = {
            "owners": [identity.id],
            "writers": list(access.get("writers") or []),
            "readers": list(access.get("readers") or []),
        }
    async with db.acquire() as conn, conn.transaction():
        row = await conn.fetchrow(
            """
                INSERT INTO projects (id, doc, created_by, updated_by)
                VALUES ($1, $2, $3, $3)
                ON CONFLICT (id) DO NOTHING
                RETURNING id, incarnation
                """,
            project_id,
            doc,
            identity.id,
        )
        if row is None:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=f"Project {project_id!r} already exists.",
            )
        await _snapshot(conn, project_id, row["incarnation"], 1, doc, identity.id)
        await broker.publish(Event(PROJECT_CREATED, project_id), conn)
    log.info("project %s created by %s", project_id, identity.id)
    return ProjectOut.from_row(project_id, doc)


@router.patch("/projects/{project_id}", response_model=ProjectOut, tags=["projects"])
async def patch_project(
    body: ProjectPatch,
    project_id: str = ProjectId,
    db: Database = Depends(get_db),
    broker: EventBroker = Depends(get_broker),
    identity: Identity = Depends(get_identity),
    settings: Settings = Depends(get_settings),
) -> ProjectOut:
    """Deep-merge the body into the stored document.

    **Atomicity.** The merge is a read-modify-write in Python, held inside a
    transaction by ``SELECT ... FOR UPDATE``. The row lock is what makes two
    concurrent PATCHes to different fields safe: the second one blocks at the
    ``SELECT`` until the first commits, then reads the *committed* document and
    merges onto it. Neither write is lost.

    The alternative -- a recursive ``jsonb`` merge in PL/pgSQL -- would also be
    atomic, and was rejected for one reason: it would be a *second*
    implementation of a merge rule whose exact semantics (arrays replace, null
    replaces, type change replaces) the browser already defines in
    ``app/js/00-core/00-util.js``. Two implementations drift; one does not. See
    ``app/merge.py``.

    Note that PostgreSQL's ``||`` operator is not an option at all: it merges
    only the top level, so ``{"items": {"s4-2": {...}}}`` would discard every
    other key under ``items``.
    """
    patch = body.root
    async with db.acquire() as conn, conn.transaction():
        row = await conn.fetchrow(
            "SELECT doc, incarnation FROM projects WHERE id = $1 FOR UPDATE",
            project_id,
        )
        if row is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"No project {project_id!r}.",
            )
        before = row["doc"] or {}
        enforced = settings.require_identity
        require(before, identity.id, "write", enforced=enforced)
        guard_access_change(before, patch, identity.id, enforced=enforced)
        guard_owner_only_fields(before, patch, identity.id, enforced=enforced)
        document = merged(before, patch)
        rev = await conn.fetchval(
            """
                UPDATE projects
                   SET doc = $2, rev = rev + 1, updated_at = now(), updated_by = $3
                 WHERE id = $1
             RETURNING rev
                """,
            project_id,
            document,
            identity.id,
        )
        await _snapshot(
            conn, project_id, row["incarnation"], rev, document, identity.id
        )
        await broker.publish(Event(PROJECT_UPDATED, project_id), conn)
    return ProjectOut.from_row(project_id, document)


@router.delete(
    "/projects/{project_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    tags=["projects"],
)
async def delete_project(
    project_id: str = ProjectId,
    db: Database = Depends(get_db),
    broker: EventBroker = Depends(get_broker),
    identity: Identity = Depends(get_identity),
    settings: Settings = Depends(get_settings),
) -> Response:
    """Delete a project and its log.

    The log goes with it by ``ON DELETE CASCADE``. That is the only way log
    rows are ever removed -- there is no endpoint that deletes an entry.
    """
    async with db.acquire() as conn, conn.transaction():
        current = await conn.fetchrow(
            "SELECT doc FROM projects WHERE id = $1 FOR UPDATE", project_id
        )
        if current is not None:
            require(
                current["doc"] or {},
                identity.id,
                "own",
                enforced=settings.require_identity,
            )
        row = await conn.fetchrow(
            "DELETE FROM projects WHERE id = $1 RETURNING id", project_id
        )
        if row is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"No project {project_id!r}.",
            )
        await broker.publish(Event(PROJECT_DELETED, project_id), conn)
    log.info("project %s deleted by %s", project_id, identity.id)
    return Response(status_code=status.HTTP_204_NO_CONTENT)


# --- version history --------------------------------------------------------

# Excluded from the fingerprint. Must match CANON_SKIP in
# app/js/00-core/12-hash.js, or the browser and the server will disagree about
# what the same record hashes to -- which is worse than having no hash, because
# it looks like evidence of a change that did not happen.
_HASH_SKIP = frozenset(
    {"updatedAt", "updatedBy", "cardUpdatedAt", "_state", "contentHash", "generated"}
)


def _canonical(value: Any) -> Any:
    """Deterministic shape: keys sorted at every depth, volatile keys dropped."""
    if isinstance(value, dict):
        return {
            k: _canonical(v) for k, v in sorted(value.items()) if k not in _HASH_SKIP
        }
    if isinstance(value, list):
        return [_canonical(v) for v in value]
    return value


def content_md5(doc: dict[str, Any]) -> str:
    """The same fingerprint the browser computes, over the same canonical form.

    MD5 because that is what the record is labeled with; it answers "is this
    the same version?" and nothing stronger. It is not a tamper seal, and
    anything that presents it as one is wrong -- see the note in the app's
    changelog view.
    """
    canon = _json.dumps(
        _canonical(doc), sort_keys=True, separators=(",", ":"), ensure_ascii=False
    )
    return hashlib.md5(canon.encode("utf-8")).hexdigest()


async def _snapshot(
    conn: Any,
    project_id: str,
    incarnation: Any,
    rev: int,
    doc: dict[str, Any],
    by: str | None,
) -> None:
    """Record one immutable version. Caller supplies the open transaction.

    The access list is copied onto the row. That is what keeps history as
    restricted as the record was: a deleted project has no live document to
    check against, and without this its snapshots were readable by anyone who
    could reach the API. See ``003_version_access.sql``.
    """
    access = doc.get("access") if isinstance(doc.get("access"), dict) else {}
    # No ON CONFLICT. A conflict here means two snapshots claim the same
    # (project, incarnation, revision), which cannot happen while the caller
    # holds the row lock -- so if it does, something is wrong and the write
    # should fail loudly. The previous DO NOTHING silently dropped the rev 1 of
    # a project that reused a deleted id, leaving a history with a missing
    # first revision and no indication of it.
    await conn.execute(
        """
        INSERT INTO project_version
               (project_id, incarnation, rev, doc, content_md5, changed_by, access)
        VALUES ($1, $2, $3, $4, $5, $6, $7)
        """,
        project_id,
        incarnation,
        rev,
        doc,
        content_md5(doc),
        by,
        access,
    )


async def _version_gate(
    conn: Any, project_id: str
) -> tuple[dict[str, Any], Any] | None:
    """Which history to read, and the access list that governs reading it.

    Returns ``(doc_for_access_check, incarnation)``, or ``None`` when there is
    no history at all -- which the caller turns into a 404.

    The incarnation matters as much as the access list. Project ids are
    caller-chosen and snapshots outlive their project, so one id can have two
    unrelated histories: the deleted project's, and the one someone created
    afterwards reusing the id. Reads are scoped to the LIVE project's
    incarnation when there is one, and to the most recent incarnation
    otherwise, so a reused id never shows two records merged into one.

    Access comes from the live project where there is one, and otherwise from
    the access list recorded on that incarnation's most recent snapshot -- so
    deleting a project does not turn its history into a public record.
    """
    live = await conn.fetchrow(
        "SELECT doc, incarnation FROM projects WHERE id = $1", project_id
    )
    if live is not None:
        return (live["doc"] or {}), live["incarnation"]
    row = await conn.fetchrow(
        """
        SELECT access, incarnation FROM project_version
         WHERE project_id = $1
         ORDER BY changed_at DESC, rev DESC
         LIMIT 1
        """,
        project_id,
    )
    if row is None:
        return None
    return {"access": row["access"] or {}}, row["incarnation"]


# --- version history --------------------------------------------------------


@router.get("/projects/{project_id}/versions", tags=["versions"])
async def list_versions(
    project_id: str = ProjectId,
    db: Database = Depends(get_db),
    settings: Settings = Depends(get_settings),
    identity: Identity = Depends(get_identity),
) -> list[dict[str, Any]]:
    """Every recorded revision of this project, newest first.

    Metadata only -- revision, fingerprint, who, when. The documents
    themselves are fetched one at a time, because returning fifty full
    snapshots to render a list is a lot of bytes for a column of dates.

    Access is checked against the live project, or -- when it has been deleted
    -- against the access list recorded on its most recent snapshot. A deleted
    project keeps its versions on purpose (see 002_versions.sql), and it must
    not become readable to everyone in the process: "it was deleted, and here
    is what it said" is the audit answer for the people who could read it, not
    for everybody with an account.
    """
    async with db.acquire() as conn:
        gate = await _version_gate(conn, project_id)
        if gate is None:
            raise HTTPException(status.HTTP_404_NOT_FOUND, "No such project")
        doc, incarnation = gate
        require(doc, identity.id, "read", enforced=settings.require_identity)
        rows = await conn.fetch(
            """
            SELECT rev, content_md5, changed_by, changed_at, purged_at, purged_by
              FROM project_version
             WHERE project_id = $1 AND incarnation = $2
             ORDER BY rev DESC
            """,
            project_id,
            incarnation,
        )
    return [
        {
            "rev": r["rev"],
            "md5": r["content_md5"],
            "by": r["changed_by"],
            "at": r["changed_at"].isoformat(),
            "purged": r["purged_at"] is not None,
            **(
                {
                    "purgedAt": r["purged_at"].isoformat(),
                    "purgedBy": r["purged_by"],
                }
                if r["purged_at"] is not None
                else {}
            ),
        }
        for r in rows
    ]


@router.get("/projects/{project_id}/versions/{rev}", tags=["versions"])
async def read_version(
    project_id: str = ProjectId,
    rev: int = 0,
    db: Database = Depends(get_db),
    settings: Settings = Depends(get_settings),
    identity: Identity = Depends(get_identity),
) -> dict[str, Any]:
    """One revision, exactly as it was stored, with its fingerprint.

    A purged revision returns an empty ``doc`` and ``purged: true``. Its
    ``md5`` is the fingerprint of the ORIGINAL content, which is what makes the
    tombstone evidence rather than a gap.
    """
    async with db.acquire() as conn:
        gate = await _version_gate(conn, project_id)
        if gate is None:
            raise HTTPException(status.HTTP_404_NOT_FOUND, "No such project")
        doc, incarnation = gate
        require(doc, identity.id, "read", enforced=settings.require_identity)
        row = await conn.fetchrow(
            """
            SELECT rev, doc, content_md5, changed_by, changed_at, purged_at, purged_by
              FROM project_version
             WHERE project_id = $1 AND incarnation = $2 AND rev = $3
            """,
            project_id,
            incarnation,
            rev,
        )
    if row is None:
        raise HTTPException(
            status.HTTP_404_NOT_FOUND, f"No revision {rev} of {project_id!r}."
        )
    out: dict[str, Any] = {
        "rev": row["rev"],
        "md5": row["content_md5"],
        "by": row["changed_by"],
        "at": row["changed_at"].isoformat(),
        "doc": row["doc"],
        "purged": row["purged_at"] is not None,
    }
    if row["purged_at"] is not None:
        out["purgedAt"] = row["purged_at"].isoformat()
        out["purgedBy"] = row["purged_by"]
    return out


@router.delete(
    "/projects/{project_id}/versions",
    status_code=status.HTTP_204_NO_CONTENT,
    tags=["versions"],
)
async def purge_versions(
    project_id: str = ProjectId,
    db: Database = Depends(get_db),
    settings: Settings = Depends(get_settings),
    identity: Identity = Depends(get_identity),
) -> Response:
    """Destroy the stored content of every retained revision. Owner only.

    This is the disposal path. Snapshots are otherwise append-only and survive
    the project's deletion, which is right for an audit trail and wrong as an
    absolute: data entered in error -- a patient identifier pasted into an
    evidence field -- has to be removable, and before this it was not
    removable through the application at all.

    What survives is deliberate. Each row keeps its revision number, its
    author, its timestamp and its ORIGINAL ``content_md5``; only ``doc`` is
    emptied, and ``purged_at``/``purged_by`` record who did it. A row that
    vanished would be indistinguishable from a snapshot never taken. A trigger
    in 003_version_access.sql permits exactly this transition and nothing else.

    Works on a deleted project, whose access list comes from its last snapshot
    -- otherwise the one record most likely to need purging would be the one
    record nobody could purge.
    """
    async with db.acquire() as conn, conn.transaction():
        gate = await _version_gate(conn, project_id)
        if gate is None:
            raise HTTPException(status.HTTP_404_NOT_FOUND, "No such project")
        doc, incarnation = gate
        require(doc, identity.id, "own", enforced=settings.require_identity)
        purged = await conn.fetchval(
            """
            WITH redacted AS (
                UPDATE project_version
                   SET doc = '{}'::jsonb, purged_at = now(), purged_by = $3
                 WHERE project_id = $1
                   AND incarnation = $2
                   AND purged_at IS NULL
             RETURNING 1
            )
            SELECT count(*) FROM redacted
            """,
            project_id,
            incarnation,
            identity.id,
        )
    log.warning(
        "version history of %s purged by %s (%d revision(s))",
        project_id,
        identity.id,
        purged or 0,
    )
    return Response(status_code=status.HTTP_204_NO_CONTENT)


# --- audit log --------------------------------------------------------------


@router.get(
    "/projects/{project_id}/log",
    response_model=list[LogEntryOut],
    tags=["audit log"],
)
async def read_log(
    project_id: str = ProjectId,
    db: Database = Depends(get_db),
    settings: Settings = Depends(get_settings),
    identity: Identity = Depends(get_identity),
) -> list[LogEntryOut]:
    """The newest entries, descending by ``at`` -- what ``subscribeLog`` shows.

    A missing project returns an empty list rather than 404. The app subscribes
    to a log and deletes a project from two different code paths, and a 404
    racing a delete would surface as an error toast for something the user just
    did on purpose.
    """
    async with db.acquire() as conn:
        # The log is the project's history; seeing it is seeing the project.
        # A missing project still returns an empty list rather than 404 -- see
        # the docstring -- so an absent row is not an access failure.
        owner_row = await conn.fetchrow(
            "SELECT doc FROM projects WHERE id = $1", project_id
        )
        if owner_row is not None:
            require(
                owner_row["doc"] or {},
                identity.id,
                "read",
                enforced=settings.require_identity,
            )
        rows = await conn.fetch(
            """
            SELECT entry FROM project_log
             WHERE project_id = $1
             ORDER BY at DESC, seq DESC
             LIMIT $2
            """,
            project_id,
            settings.log_page_size,
        )
    return [LogEntryOut(**row["entry"]) for row in rows]


@router.post(
    "/projects/{project_id}/log",
    response_model=LogEntryOut,
    status_code=status.HTTP_201_CREATED,
    tags=["audit log"],
)
async def append_log(
    body: LogEntryIn,
    project_id: str = ProjectId,
    db: Database = Depends(get_db),
    broker: EventBroker = Depends(get_broker),
    identity: Identity = Depends(get_identity),
    settings: Settings = Depends(get_settings),
) -> LogEntryOut:
    """Append one entry. There is no update and no delete, by design.

    ``at`` and ``by`` are **overwritten** here, with the server clock and the
    proxy identity, even though the browser sends both. An audit log whose
    author and timestamp come from the client is not an audit log -- it is a
    field the client can set. A trigger in ``001_init.sql`` blocks ``UPDATE``
    on this table so a later bug cannot rewrite history either.
    """
    entry: dict[str, Any] = body.model_dump()
    now = datetime.now(UTC)
    entry["at"] = now.isoformat(timespec="milliseconds")
    entry["by"] = identity.id

    async with db.acquire() as conn, conn.transaction():
        target = await conn.fetchrow(
            "SELECT doc FROM projects WHERE id = $1", project_id
        )
        if target is not None:
            require(
                target["doc"] or {},
                identity.id,
                "write",
                enforced=settings.require_identity,
            )
        try:
            await conn.execute(
                """
                    INSERT INTO project_log (project_id, at, by_id, entry)
                    VALUES ($1, $2, $3, $4)
                    """,
                project_id,
                now,
                identity.id,
                entry,
            )
        except asyncpg.ForeignKeyViolationError as exc:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"No project {project_id!r}.",
            ) from exc
        await broker.publish(Event(LOG_APPENDED, project_id), conn)
    return LogEntryOut(**entry)


# --- change stream ----------------------------------------------------------


@router.get("/events", tags=["events"])
async def events(
    request: Request,
    broker: EventBroker = Depends(get_broker),
    settings: Settings = Depends(get_settings),
    _: Identity = Depends(get_identity),
) -> StreamingResponse:
    """One ``text/event-stream`` event per change, for as long as you hold it.

    Events carry an id, never a document, so the stream stays well under
    ``NOTIFY``'s 8000-byte payload cap no matter how large a project grows. The
    client refetches what changed.

    The comment heartbeat matters more than it looks: Cloud Run, an ALB and
    Azure Front Door all close an idle connection, and an SSE stream with
    nothing to say is indistinguishable from a dead one until a byte moves.
    """

    async def stream() -> AsyncIterator[str]:
        async with broker.subscribe() as queue:
            # Tell EventSource how long to wait before reconnecting, and send
            # one frame immediately so proxies that buffer until first byte
            # release the response headers.
            yield "retry: 3000\n\n"
            yield Event("hello", None, _now_iso()).sse()
            while True:
                if await request.is_disconnected():
                    return
                try:
                    event = await asyncio.wait_for(
                        queue.get(), timeout=settings.sse_keepalive_seconds
                    )
                except TimeoutError:
                    yield ": ping\n\n"
                    continue
                yield event.sse()

    return StreamingResponse(
        stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache, no-store, no-transform",
            "Connection": "keep-alive",
            # nginx and anything derived from it buffer proxied responses by
            # default, which turns a live stream into a long silence.
            "X-Accel-Buffering": "no",
        },
    )
