#!/usr/bin/env python3
"""Generate the OPTICA framework's data module from data/optica_items.json.

One source of truth: the same file that produces the published OPTICA checklist
page produces the app's copy of the items. Editing the paraphrases in one place
updates both.

Run via: pixi run gen-docs
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "optica_items.json"
OUT = ROOT / "app" / "js" / "10-frameworks" / "20-optica" / "00-definition.js"

HEADER = """/* ============================================================
   OPTICA: content
   GENERATED by scripts/gen_optica_module.py from
   data/optica_items.json -- do not edit by hand.

   Item wording is this project's own paraphrase. The OPTICA paper
   (NEJM AI 2024) is copyright Massachusetts Medical Society and
   marked for personal use only; its text is not reproduced here or
   anywhere in this repository.

   Item keys are dot-free ("7-11", not "7.11") because the app's
   edit()/get() helpers split state paths on ".", so a dotted key
   cannot be addressed. The dotted form is display only.
   ============================================================ */
"""


def main() -> int:
    data = json.loads(DATA.read_text(encoding="utf-8"))
    chapters = data["chapters"]
    total = sum(len(c["items"]) for c in chapters)
    if total != 77:
        print(f"error: expected 77 OPTICA items, found {total}", file=sys.stderr)
        return 1

    payload = {
        "domains": data["domains"],
        "chapters": [
            {
                "n": c["number"],
                "domain": c["domain"],
                "title": c["title"],
                "purpose": c.get("purpose", ""),
                "items": [
                    {
                        "key": i["id"].replace(".", "-"),
                        "num": i["id"],
                        "text": i["paraphrase"],
                        "who": i.get("producer", ""),
                        "stage": i.get("stage", ""),
                        "rel": i.get("relation", ""),
                        "chai": i.get("chaiIds", []),
                    }
                    for i in c["items"]
                ],
            }
            for c in chapters
        ],
    }

    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        HEADER
        + "const OPTICA = "
        + body
        + ";\n"
        + "const OPTICA_ITEMS = OPTICA.chapters.flatMap(c => "
        "c.items.map(i => ({ ...i, chapter: c })));\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({total} items, {len(chapters)} chapters)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
